# Generated by Django 5.2.16 on 2026-07-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('FARMER', 'Farmer / Agriculturalist'), ('EXPERT', 'Agronomist Expert'), ('BUYER', 'Crop Buyer / Trader'), ('ADMIN', 'Enterprise Admin')], default='FARMER', max_length=20),
        ),
    ]
