version: '3.8'

services:
  urvixa-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: urvixa_production_app
    restart: always
    ports:
      - "80:80"
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=urvixa-production-secret-key-agri-ai-suite-2026
      - ALLOWED_HOSTS=*
    volumes:
      - ./backend/db.sqlite3:/app/backend/db.sqlite3
